name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set write permissions
        run: chmod -R u+w .

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debug build output
        run: ls -la dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set write permissions
        run: chmod -R u+w .

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: dist

      - name: Debug artifact directory
        run: ls -la dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
